name: Build and Release

on:
  push:
    branches: [main, master]
    tags:
      - "v*"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".gitignore"

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.5"
          check-latest: false
          cache: false

      - name: Download dependencies
        run: go mod download -x

      - name: Run tests
        run: go test ./...
        env:
          CGO_ENABLED: 0

  release:
    name: Build and Release
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.5"

      - name: Download dependencies
        run: go mod download -x

      - name: Run tests
        run: go test ./...
        env:
          CGO_ENABLED: 0

      - name: Build executables
        run: |
          if (Test-Path -Path build) { Remove-Item -Path build -Recurse -Force }
          mkdir build
          go build -o build/ecf-sequence.exe -ldflags="-s -w" ./cmd/server
          go build -o build/install.exe -ldflags="-s -w" ./cmd/install
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path build\*.exe -DestinationPath build\ecf-sequence.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build\ecf-sequence.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
