name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".gitignore"

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.5"
          check-latest: false
          cache: false

      - name: Download dependencies
        run: go mod download -x

      - name: Run tests
        run: go test -timeout 30s ./...
        env:
          CGO_ENABLED: 0
