name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".gitignore"

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest

    # Previene ejecuciones redundantes
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Usar una versión específica de Go en lugar de la última
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.5" # Versión específica en lugar de "1.23"
          check-latest: false # No buscar actualizaciones

      # Descargar dependencias en modo verify
      - name: Download dependencies
        run: go mod download -x

      # Ejecutar tests con timeout
      - name: Run tests
        run: go test -timeout 30s ./...
        env:
          CGO_ENABLED: 0 # Deshabilitar CGO para builds más rápidos
